In [2]:
import numpy as np
from datascience import *

%matplotlib inline

In [3]:
cah = Table.read_table('201709-CAH_PulseOfTheNation.csv')

In [4]:
cah.show(5)

In [5]:
cah.group('Political Affiliation')

Political Affiliation | count
DK/REF                | 31
Democrat              | 87
Independent           | 120
Republican            | 72

In [9]:
cah.column('Political Affiliation') == 'Democrat'

array([ True, False, False,  True, False, False,  True,  True, False,
        True,  True, False, False,  True, False,  True, False,  True,
        True, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True, False, False, False,  True, False, False, False,
       False,  True,  True, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False,  True, False,  True, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False,

In [12]:
cah_affiliation = cah.with_columns('Democrat', cah.column('Political Affiliation') == 'Democrat',
                'Republican', cah.column('Political Affiliation') == 'Republican',
                'Independent', cah.column('Political Affiliation') == 'Independent'). drop('Political Affiliation')

In [13]:
cah_affiliation.show(5)

In [14]:
cah.group('Believe in Ghosts')

Believe in Ghosts | count
DK/REF            | 8
No                | 187
Yes               | 115

In [16]:
cah.select('Believe in Ghosts')

Believe in Ghosts
No
No
No
No
Yes
No
No
No
Yes
Yes
... (300 rows omitted)

In [17]:
def believe_in_ghosts(answer):
    return answer == 'Yes'

In [18]:
def doesnt_believe_in_ghosts(answer):
    return answer == 'No'

In [19]:
def believe_in_ghosts(answer):
    if answer == 'Yes':
        return 1
    else:
        return 0

In [20]:
def doesnt_believe_in_ghosts(answer):
    if answer == 'No':
        return 1
    else:
        return 0

In [22]:
cah.with_columns('Believes in Ghosts', cah.apply(believe_in_ghosts, 'Believe in Ghosts'),
                 'Does not Believe in Ghosts', cah.apply(doesnt_believe_in_ghosts, 'Believe in Ghosts'))

Income | Gender | Age  | Age Range | Political Affiliation | Transformer Movies | Level of Education | Believe in Ghosts | Believes in Ghosts | Does not Believe in Ghosts
68000  | Female | 56   | 55-64     | Democrat              | 0                  | High school        | No                | 0                  | 1
46000  | Male   | 63   | 55-64     | Independent           | 0                  | Some college       | No                | 0                  | 1
51000  | Male   | 48   | 45-54     | Republican            | 0                  | High school        | No                | 0                  | 1
54000  | Female | 64   | 55-64     | Democrat              | 0                  | Some college       | No                | 0                  | 1
83000  | Male   | 61   | 55-64     | Independent           | 0                  | College degree     | Yes               | 1                  | 0
90000  | Female | 64   | 55-64     | Republican            | 0                  | High school        | No                | 0                  | 1
5000   | Female | 68   | 65+       | Democrat              | 0                  | Some college       | No                | 0                  | 1
57000  | Female | 63   | 55-64     | Democrat              | 0                  | College degree     | No                | 0                  | 1
47000  | Female | 44   | 35-44     | Independent           | 1                  | High school        | Yes               | 1                  | 0
39000  | Female | 57   | 55-64     | Democrat              | 0                  | College degree     | Yes               | 1                  | 0
... (300 rows omitted)

In [23]:
cah.group('Level of Education')

Level of Education | count
College degree     | 106
Graduate degree    | 80
High school        | 54
Other              | 5
Some college       | 65

In [25]:
cah.select('Level of Education')

Level of Education
High school
Some college
High school
Some college
College degree
High school
Some college
College degree
High school
College degree
... (300 rows omitted)

In [28]:
college_degree = cah.column('Level of Education') == 'College degree'
graduate_degree = cah.column('Level of Education') == 'Graduate degree'

In [32]:
college_degree | graduate_degree

array([False, False, False, False,  True, False, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False, False,  True, False,  True, False, False,  True, False,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False, False,  True, False,  True, False,  True,  True,
       False, False,  True,  True, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False,  True,  True, False,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
       False,  True,

In [30]:
graduate_degree

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
        True, False,  True,  True,  True, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True,  True,
        True, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True,

In [24]:
def college_or_higher(answer):
    if answer == 'College degree':
        return 1
    if answer == 'Graduate degree':
        return 1
    else:
        return 0

In [26]:
cah.apply(college_or_higher, 'Level of Education')

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1,